### ISSUE TITLE
SBOM signing

### ISSUE THREAD

**Issue by winterrocks** [OpenChain-Project/Telco-WG#1]
Now that we have this GH repo, I thought that maybe this is a good place to gather some thoughts for the SBOM standard. 

One issue we have been discussing is how one can be sure that the SBOM provided is really for the SW provided. OpenSSF has a sigstore project: https://www.sigstore.dev/ that may give the answer or at least give direction for the answer. 

If someone who is more expert on this, can have a look and share thoughts on this.

**Comment by vargenau** [comment]
Fixed by https://github.com/OpenChain-Project/Telco-WG/pull/45
