### ISSUE TITLE
OpenChain Telco SBOM Validator shows no errors, but SPDX is non compliant

### ISSUE THREAD

**Issue by agustingroh** [OpenChain-Project/Telco-WG#110]
Hi!
I am using the `openchain-telco-sbom-validator `to validate my SPDX output. Although the error table is empty, the validator still shows a message saying the SPDX is not compliant with the OpenChain Telco SBOM Guide.

I've attached some files for reference.
[scanoss-engine.spdx.json](https://github.com/user-attachments/files/17309954/scanoss-engine.spdx.json)
![image](https://github.com/user-attachments/assets/07fa7e0b-b92d-4c94-b30f-81e6048e2979)

**Comment by vargenau** [comment]
Hi Agustin,
I confirm the issue.
We will look after it.

**Comment by CsatariGergely** [comment]
@agustingroh thanks for the report. I fixed it in here: https://github.com/OpenChain-Project/Telco-WG/pull/111
I'm using the SBOM you provided in the test. I hope it is ok :)
