### ISSUE TITLE
Request for an Example: OpenChain Telco SBOM Guide Compatibility

### ISSUE THREAD

**Issue by agustingroh** [OpenChain-Project/Telco-WG#115]
Hello,

We’re looking for an example that shows how to align with the OpenChain Telco SBOM Guide. An example illustrating best practices or standard implementations would help us in aligning our work with the guidelines outlined in the OpenChain Telco SBOM Guide.

Regards,

Agustin

**Comment by shanecoughlan** [comment]
Hi @agustingroh 

It's great to hear that you are working on alignment and support.

This question should be directed to (overall SBOM work) https://lists.openchainproject.org/g/sbom and/or https://lists.openchainproject.org/g/telco (the specific group that started the telco guide) for the community to engage and respond. Some members - like Nokia - have been very active.

**Comment by vargenau** [comment]
Hi @agustingroh 

You can find an example of SBOM conforming to the OpenChain Telgo Guide at:
https://github.com/OpenChain-Project/Telco-WG/tree/main/tools/openchain_telco_sbom_validator/open-source-compliance-artifacts

If you have questions, do not hesitate to post a message at https://lists.openchainproject.org/g/telco as Shane proposed, or reach to me directly at mailto:marc-etienne.vargenau@nokia.com
