### ISSUE TITLE
Allow PackageVerificationCode also

### ISSUE THREAD

**Issue by vargenau** [OpenChain-Project/Telco-WG#121]
In the guide version 1.0, we require PackageChecksum in order to comply with the "NTIA SBOM Minimum elements" for "Component Hash".

However, SPDX 2 provides two possibilities for this, PackageChecksum and PackageVerificationCode.

So I propose to allow both.

For example, SBOMs generate by Yocto provide PackageVerificationCode and not PackageChecksum.

The newly published CISA document "Framing Software Component Transparency: Establishing a Common Software Bill of Materials (SBOM), Third Edition"
https://www.cisa.gov/resources-tools/resources/framing-software-component-transparency-2024
allows both, see table in section 2.5.

**Comment by winterrocks** [comment]
I guess that for backwards compatibility the PackageVerificationCode should be allowed. 

https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Classes/PackageVerificationCode/ says:
> This verification method is provided for compatibility with SPDX 2.X.
> 
> Use of this verification code method is **discouraged** except for scenarios where the contentIdentifier property on Artifact can not be used.

I added the **highlighting**.
