### ISSUE TITLE
the wording in the Package information of section 3.2

### ISSUE THREAD

**Issue by MasahiroDAIKOKU** [OpenChain-Project/Telco-WG#138]
**Suggestion to change the wording**

The following semantics in section 3.2 may seem contradictory.
 - “Component Hash” is recommended by the “NTIA SBOM Minimum elements”, and it maps to "PackageChecksum" or "PackageVerificationCode" in SPDX.
 - PackageChecksum: recommended by “NTIA SBOM Minimum elements” 
 <br>

So, how about changing the wording of the seventh bullet point in the Package information in section 3.2 as follows?
 - PackageChecksum: recommended by “NTIA SBOM Minimum elements"
    => 
 - PackageChecksum: or PackageVerificationCode: recommended by “NTIA SBOM Minimum elements”

**Comment by vargenau** [comment]
Hello @MasahiroDAIKOKU 
Thank you for your report.
That was an overlook.
I have now removed the PackageChecksum for the list of MANDATORY package information.
There is now a new clause under the list:

> One of the two attributes PackageChecksum or PackageVerificationCode is MANDATORY:
> recommended by “NTIA SBOM Minimum elements”
