### ISSUE TITLE
[Bug] The specification should state the license.

### ISSUE THREAD

**Issue by stephenkilbaneadi** [OpenChain-Project/Telco-WG#3]
## **Describe the bug**
The main License Compliance spec states that it is CC0-1.0 in the Introduction. We should do that for this spec, too.

**Comment by shanecoughlan** [comment]
Quick clarification: the [license compliance spec (ISO/IEC 5230)](https://github.com/OpenChain-Project/License-Compliance-Specification/blob/master/Official/en/2.1/openchainspec-2.1.md) is "licensed under [Creative Commons Attribution License 4.0](https://creativecommons.org/licenses/by/4.0/) (CC-BY-4.0)."

But concur that we should fix the statement of license in the Telco spec.

@Jimmy-ahlberg checking why the spec is CC-0? It's fine, but that allows editing/forking, so we probably need to expand on the why in the intro.

**Comment by shanecoughlan** [comment]
Fixed and closing this issue.
