### ISSUE TITLE
We need a good name for the specification. 

### ISSUE THREAD

**Issue by vargenau** [OpenChain-Project/Telco-WG#41]
We need a good name for the specification. Currently in the document we have:
•	OpenChain Telecommunications Group SBOM Specification
•	OpenChain Telco SBOM specification
•	Telco Standard SBOM
•	telco standard SBOM
•	Telco Group SBOM specification
•	Telco SBOM specification
•	Telco Profile of SPDX

As for the naming for the specification, is there an interface to propose our preference? If not,  my proposal is to go with  
“OpenChain Telco SBOM specification”. 

Regards,
Prasad Iyer (Director, Product Operations - Cisco) 

Proposal:
- “OpenChain Telco SBOM specification” as a full name
- "Telco SBOM" as a short name

**Comment by stephenkilbaneadi** [comment]
If we're going to have a full name and a short name, can should the full name be "Telecommunications Group" rather than "Telco"?

**Comment by stephenkilbaneadi** [comment]
Having looked at the corresponding PR, I now understand better. "Telco SBOM" is the name of the SBOM defined by the spec, so it makes sense that the spec name should be "OpenChain Telco SBOM Specification"

**Comment by stephenkilbaneadi** [comment]
Addressed by PR #42
