### ISSUE TITLE
[Improvement]

### ISSUE THREAD

**Issue by stephenkilbaneadi** [OpenChain-Project/Telco-WG#43]
## **Describe the improvement**
Add to rationale in 3.6.7 to give background on why Tag:Value is the selected required data format.
**Additional context**
The Tag:Value format is one of the harder formats to parse, so it would be good to explain why this choice was made (for future editors of the specification).

**Comment by vargenau** [comment]
Fixed by https://github.com/OpenChain-Project/Telco-WG/pull/47
