### ISSUE TITLE
[Question] Content and quality of SBOMs

### ISSUE THREAD

**Issue by MasahiroDAIKOKU** [OpenChain-Project/Telco-WG#52]
## Question
In some cases, SBOMs are generated using fee-based SCA tools, and in other cases, SBOMs are generated using open source software-based tools.
Is it currently possible to keep the content and quality of the SBOM completely constant, independent of the tool or software used to generate the SBOM?

## Suggested Solution
If it is practically difficult to keep the content and quality of the SBOM constant, we think that one approach is to state the following with regard to the tool generating the SBOM.

- Name of the manufacturer of the software or SCA tool
- Name of the software or SCA tool
- Version of the software or SCA tool

In this case, we think that an option to provide these information of the tool or software used to generate the SBOM should be defined using a field somewhere in the SPDX.

We would appreciate your comments.

**Comment by vargenau** [comment]
Hi Masa-san,

This is a good suggestion.

Let us discuss it in our next call.

Best regards,

Marc-Etienne

From: Masa DAIKOKU ***@***.***>
Sent: Wednesday, May 3, 2023 5:39 PM
To: OpenChain-Project/Telco-WG ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenChain-Project/Telco-WG] [Question] Content and quality of SBOMs (Issue #52)

Question

In some cases, SBOMs are generated using fee-based SCA tools, and in other cases, SBOMs are generated using open source software-based tools.
Is it currently possible to keep the content and quality of the SBOM completely constant, independent of the tool or software used to generate the SBOM?

Suggested Solution

As the content and quality of the SBOM depends on the tool or software generating the SBOM, if it cannot be kept constant at present, one option would be to state the following with regard to the tool generating the SBOM

  *   Name of the manufacturer of the software or tool
  *   Name of the software or tool
  *   Version of the software or tool

In this case, we think that an option to provide these information of the tool or software used to generate the SBOM should be defined using a field somewhere in the SPDX.

We would appreciate your comments.

**Comment by Jimmy-ahlberg** [comment]
This seems like a very good idea to me. In case I'm not able to make next call I would like to add my support here.

**Comment by stephenkilbaneadi** [comment]
While I think this is a great idea, it _is_ dependent on the SBOM-generating tool providing the content, or requiring post-generation edits. If a commercial tool doesn't already provide this information (which, IMO, _every_ SBOM generator should provide), they may require some convincing to adopt this.

If SPDX-3.0 doesn't already require this, maybe this is feedback we can provide. :-)

**Comment by MasahiroDAIKOKU** [comment]
@vargenau @shanecoughlan @Jimmy-ahlberg 

Thank you very much for your good feedbacks.

We have not actually compared the content and quality of SBOM created with OSS-based SCA software with the content and quality of SBOM created with paid-for SCA software, due to cost and human resource limitations.

In fact, the SCA software market is growing and we assume that the content and quality of SBOM will be a concern in the future.

If this is a requirement for SPDX 3.0, we would be grateful for your support.

Masa

**Comment by Jimmy-ahlberg** [comment]
I think this would make a great additions for SPDX 3.X.  Happy to support that. 

In the meantime we could perhaps add it to the specification here to show the SPDX community how it would work? 

Without going into the details, we use a few SCA tools internally, both paid and free, they all have their respective strengths and weaknesses, having the information about the tool used to generate the SBOM would be useful. I assume that there is at least some "security" aspect to this information as well, in case it turns out a certain SCA tool of a specific version consistently missed certain pieces of software for whatever reason. That would be very good to know if one got a SBOM generated by that SCA tool of that version.

**Comment by MasahiroDAIKOKU** [comment]
Thank you for your response.  I completely agree with your comment that we should add to this Telco SBOM Spec. document what we require regarding SBOM generation tools.

As you pointed out, requesting this information would also contribute to the security of the overall system developed using the OSS.
Do you have any other ideas of what to require in addition to the three points I suggested in my first post?
  *   Name of the manufacturer of the software or tool
  *   Name of the software or tool
  *   Version of the software or tool
  
  
And, thank you for the very useful feedback from your real experience.
If we have difference between SBOMs generated by using fee-based SCA tools and ones generated by using open source software-based tools, I think we may have to understand the following points at least.
  *   Quality level of individual SBOM tools
  *   Quality difference between quality level considered sufficient in the Telco software supply chain and quality level of individual SBOM tools
  *   SBOM tools that exceed quality level considered sufficient in the Telco software supply chain
 
To achieve these thought, it may be necessary to establish "OpenChain Certification Programs for SBOM generation tool"  and "Telco SBOM Quality specifications".

**Comment by MasahiroDAIKOKU** [comment]
@stephenkilbaneadi 

As you pointed out, I also think commercial SBOM generation tools do not yet provide these information I raised. 
Also, it may take some persuasion for the SCA development vendors  to adopt these points.

As a happy story, if the SCA development vendors can embed their company name or the name of their SCA tool in SBOM data format, there may be a advertising effect there.
If the SCA development vendors considers that there is a promotional effect for SCA company's marketing, it may lead to a smooth adoption of the commercial SCA tools.

**Comment by vargenau** [comment]
Thank you all for your comments.

If we want to include the following in the Telco SBOM:
- Name of the manufacturer of the software or tool
- Name of the software or tool
- Version of the software or tool

it can be done in the SPDX Creator field.

The Creator field is mandatory, it can contain one or more lines of the form:
```
"Person: person name" and optional "(email)"
"Organization: organization" and optional "(email)"
"Tool: toolidentifier-version"
```

So we can make it mandatory to have:
- a line with the Organization keyword
- a line with the Tool keyword; in the line we MUST have after the Tool keyword the tool name and the tool version
The tool name and the tool version SHOULD be separated by hyphen ("-"), no other hyphen SHOULD appear on the line.

The SPDX standard gives "toolidentifier-version" as an example, but it is not mandatory to have this syntax. For example, there is a tool that outputs:
```
Creator: Tool: sigs.k8s.io/bom/pkg/spdx
```
We have also:
```
Creator: Tool: scancode-toolkit 30.1.0
```
and
```
Creator: Tool: SCANOSS-PY: 1.5.1
```
where the name contains an hyphen, and the tool name and tool version are not separated by an hyphen.

So I do not think we can require a precise syntax.

Let us discuss the details in our next call.

**Comment by CsatariGergely** [comment]
@MasahiroDAIKOKU OpenSSF has an [SBOMs are everywhere WG](https://github.com/ossf/sbom-everywhere) with the aim to compare SBOM generators.

**Comment by MasahiroDAIKOKU** [comment]
@CsatariGergely 
Thank you very much for the very useful information.
Is this the document in the link below?   Very interesting.
https://docs.google.com/document/d/1UeV0BhZHKBIJY8fi40hAly3jP_dH9u7Nao4Alw8fY0Y/edit#

**Comment by MasahiroDAIKOKU** [comment]
If possible, please provide examples of creator field descriptions in the following cases in order to ensure correct understanding.

- Name of the person to create the SPDX document :  Jane Doe
- Name of the organization to create the SPDX document :  Foo Technology   (Companies Jane belongs to)
- Name of the manufacturer of the software or tool :   Bar  company
- Name of the software or tool :  baz software
- Version of the software or tool :  1.0.1.0
